config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users do
    get  'chat',   to: 'microposts#chat'
    post 'create', to: 'microposts#create'
  end

  root 'users#index'
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/helpers.rb
module Helpers
  extend ActiveSupport::Concern

  included do
    before_action :authenticate_user!
    before_action :set_user
  end

  private
    def set_user
      @user = User.find(params[:id]) if params[:id]
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  include Helpers

  def chat
    @micropost = Micropost.new
  end

  def create
    @micropost = Micropost.new(micropost_params)
    if @micropost.save
      WebsocketRails[:posts].trigger 'chat', @micropost
      render json: { status: 200 }
    end
  end

  private
    def micropost_params
      params.require(:micropost).permit(:body, :owner)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Helpers

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebsocMy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class='container'>
    <ul class='header content'>
      <%  unless user_signed_in? %>
        <li>
          <%= link_to 'Sign In', new_user_session_path %>
        </li>
        <li>
          <%= link_to 'Sign Up', new_user_registration_path %>
        </li>
      <% end %>
      <li>
        <%= link_to 'Sign Out', destroy_user_session_path, method: 'delete' if user_signed_in? %>
      </li>
    </ul>
  </div>

  <div class='container'>
    <%= yield %>
  </div>

</body>
</html>

app/views/microposts/chat.haml
.websockets
  %ul
    %li
      .chat#user1
        %p chat1
        .chat-massages
        .input-area
          %input
          %p
            %button
              submit
    %li
      .chat#user2
        %p chat2
        .chat-massages
        .input-area
          %input
          %p
            %button
              submit
    %li
      .chat#user3
        %p chat3
        .chat-massages
        .input-area
          %input
          %p
            %button
              submit

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Chat', user_chat_path(user) %>
        <td><%#= link_to 'Show', user %></td>
        <td><%#= link_to 'Edit', edit_user_path(user) %></td>
        <td><%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>